version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "getPokemonStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uz1imzlj6ncg"
s3_prefix = "getPokemonStack"
region = "us-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
