version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworldstack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uz1imzlj6ncg"
s3_prefix = "helloworldstack"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
